# Generated by Django 6.0.4 on 2026-04-24 18:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('commission_type', models.CharField(choices=[('percentage', 'Percentage (%)'), ('flat', 'Flat Amount (৳)')], default='percentage', max_length=15)),
                ('commission_value', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('minimum_withdrawal_amount', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=8)),
                ('cookie_lifetime_days', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commission Setting',
                'verbose_name_plural': 'Commission Settings',
            },
        ),
        migrations.CreateModel(
            name='AffiliateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=20)),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('nid_number', models.CharField(blank=True, max_length=30)),
                ('how_will_promote', models.TextField()),
                ('preferred_payment_method', models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad')], default='bkash', max_length=10)),
                ('payment_account_number', models.CharField(blank=True, max_length=30)),
                ('balance_pending', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('balance_approved', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('balance_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_reseller', models.BooleanField(default=False)),
                ('is_fraud_flagged', models.BooleanField(db_index=True, default=False)),
                ('admin_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Affiliate Profile',
                'verbose_name_plural': 'Affiliate Profiles',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='FraudFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('self_referral', 'Self-Referral Attempt'), ('ip_abuse', 'IP Address Abuse'), ('duplicate_commission', 'Duplicate Commission Attempt'), ('suspicious_pattern', 'Suspicious Order Pattern'), ('manual', 'Manually Flagged by Admin')], db_index=True, max_length=30)),
                ('details', models.TextField()),
                ('order_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_flags', to='affiliate.affiliateprofile')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_fraud_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fraud Flag',
                'verbose_name_plural': 'Fraud Flags',
                'ordering': ['-flagged_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('user_agent', models.TextField(blank=True)),
                ('landing_url', models.URLField(blank=True, max_length=500)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('clicked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='affiliate.affiliateprofile')),
                ('referred_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_clicks_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral Click',
                'verbose_name_plural': 'Referral Clicks',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField(db_index=True)),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=15)),
                ('is_fraud_suspected', models.BooleanField(db_index=True, default=False)),
                ('fraud_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='affiliate.affiliateprofile')),
                ('referred_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions_generated', to=settings.AUTH_USER_MODEL)),
                ('commission_setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliate.commissionsetting')),
                ('referral_click', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliate.referralclick')),
            ],
            options={
                'verbose_name': 'Commission',
                'verbose_name_plural': 'Commissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResellerPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField(db_index=True)),
                ('base_price_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reseller_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseller_prices', to='affiliate.affiliateprofile')),
            ],
            options={
                'verbose_name': 'Reseller Pricing',
                'verbose_name_plural': 'Reseller Pricing',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('payment_method', models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad')], max_length=10)),
                ('payment_account', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], db_index=True, default='pending', max_length=15)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('admin_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='affiliate.affiliateprofile')),
            ],
            options={
                'verbose_name': 'Withdrawal Request',
                'verbose_name_plural': 'Withdrawal Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddIndex(
            model_name='affiliateprofile',
            index=models.Index(fields=['status', 'is_fraud_flagged'], name='affiliate_a_status_a02b55_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudflag',
            index=models.Index(fields=['affiliate', 'is_resolved'], name='affiliate_f_affilia_b5402f_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudflag',
            index=models.Index(fields=['reason', 'is_resolved'], name='affiliate_f_reason_7f5ee8_idx'),
        ),
        migrations.AddIndex(
            model_name='referralclick',
            index=models.Index(fields=['affiliate', 'ip_address'], name='affiliate_r_affilia_782830_idx'),
        ),
        migrations.AddIndex(
            model_name='referralclick',
            index=models.Index(fields=['affiliate', 'clicked_at'], name='affiliate_r_affilia_fb5ccc_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['affiliate', 'status'], name='affiliate_c_affilia_0a38c6_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['status', 'is_fraud_suspected'], name='affiliate_c_status_dda908_idx'),
        ),
        migrations.AddConstraint(
            model_name='commission',
            constraint=models.UniqueConstraint(fields=('affiliate', 'order_id'), name='unique_commission_per_order'),
        ),
        migrations.AddIndex(
            model_name='resellerpricing',
            index=models.Index(fields=['affiliate', 'is_active'], name='affiliate_r_affilia_d531f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='resellerpricing',
            constraint=models.UniqueConstraint(fields=('affiliate', 'product_id'), name='unique_reseller_price_per_product'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['affiliate', 'status'], name='affiliate_w_affilia_00ef8b_idx'),
        ),
    ]
