# Generated by Django 6.0.4 on 2026-04-25 15:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCommissionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('product_name', models.CharField(blank=True, help_text='Auto-filled label — for admin display only', max_length=220)),
                ('commission_type', models.CharField(choices=[('percentage', 'Percentage (%)'), ('flat', 'Flat Amount (৳)')], default='percentage', max_length=15)),
                ('commission_value', models.DecimalField(decimal_places=2, help_text='Percentage or flat BDT amount', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Commission Setting',
                'verbose_name_plural': 'Product Commission Settings',
                'ordering': ['product_id'],
            },
        ),
        migrations.AddField(
            model_name='commissionsetting',
            name='product_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Leave blank for a global/default rate. Set to a Product ID for per-product rate.', null=True),
        ),
    ]
