# Generated by Django 6.0.4 on 2026-04-24 19:54

import django.core.validators
import django.db.models.deletion
import store.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, help_text='Category banner/thumbnail image', null=True, upload_to=store.models.category_image_path)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Lower number = shown first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_fee_inside_dhaka', models.DecimalField(decimal_places=2, default=Decimal('60.00'), help_text='Delivery fee for Dhaka city (৳)', max_digits=8)),
                ('delivery_fee_outside_dhaka', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Delivery fee for outside Dhaka (৳)', max_digits=8)),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Free delivery for orders above this amount (0 = disabled)', max_digits=8)),
                ('site_name', models.CharField(default='AlphaCue Imports', max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('sku', models.CharField(blank=True, help_text='Auto-generated if left blank', max_length=60, unique=True)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.CharField(blank=True, help_text='Shown on product listing cards', max_length=300)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Show on homepage featured section')),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Red / Large' or 'Blue 128GB' — shown to buyer", max_length=150)),
                ('sku', models.CharField(blank=True, help_text='Auto-generated if left blank', max_length=80, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Selling price in ৳', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('compare_price', models.DecimalField(blank=True, decimal_places=2, help_text='Crossed-out original price (optional)', max_digits=10, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('track_stock', models.BooleanField(default=True, help_text='Uncheck to allow unlimited orders')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=store.models.product_image_path)),
                ('alt_text', models.CharField(blank=True, help_text='Accessibility alt text for this image', max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary image shown on listing cards')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
                ('variant', models.ForeignKey(blank=True, help_text='Link image to a specific variant (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='store.productvariant')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['-is_primary', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='VariantAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='e.g. Color, Size, Storage', max_length=50)),
                ('value', models.CharField(help_text='e.g. Red, XL, 128GB', max_length=100)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='store.productvariant')),
            ],
            options={
                'verbose_name': 'Variant Attribute',
                'verbose_name_plural': 'Variant Attributes',
                'ordering': ['key', 'value'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='store_produ_categor_591340_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured', 'is_active'], name='store_produ_is_feat_74e391_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'is_active'], name='store_produ_product_cd7aec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='variantattribute',
            unique_together={('variant', 'key')},
        ),
    ]
