# Generated by Django 6.0.4 on 2026-08-05 02:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Short reference, e.g. 1010. Grouped by type — see the seed command.', max_length=10, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Account'), ('mobile_money', 'Mobile Money (bKash / Nagad)'), ('receivable', 'Money Owed To Us'), ('inventory', 'Stock Value'), ('goods_in_transit', 'Goods In Transit'), ('loan_receivable', 'Loan Given Out'), ('expense', 'Expense'), ('payable', 'Money We Owe'), ('equity', 'Owner / Investor Capital'), ('loan_payable', 'Loan Taken'), ('income', 'Income')], db_index=True, max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('party_type', models.CharField(blank=True, choices=[('client', 'Client'), ('supplier', 'Supplier'), ('investor', 'Investor'), ('lender', 'Lender / Borrower')], db_index=True, default='', help_text='Set when this account belongs to one client / supplier / investor / lender.', max_length=20)),
                ('party_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive accounts cannot be posted to. Existing history is kept.')),
                ('is_system', models.BooleanField(default=False, help_text='Created by the chart-of-accounts seed. Should not be deleted.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['type', 'is_active'], name='finance_acc_type_d51131_idx'), models.Index(fields=['party_type', 'party_id'], name='finance_acc_party_t_9a9fd6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='The date the money actually moved.')),
                ('description', models.CharField(max_length=255)),
                ('source_type', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('source_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_reversed', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transactions', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.ForeignKey(blank=True, help_text='Set when this transaction exists to undo another one.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='finance.transaction')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Signed. Positive = into an asset or a cost; negative = out of an asset, or income.', max_digits=14)),
                ('memo', models.CharField(blank=True, default='', max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='finance.account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.transaction')),
            ],
            options={
                'verbose_name': 'Transaction Line',
                'verbose_name_plural': 'Transaction Lines',
                'ordering': ['-amount', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date', 'id'], name='finance_tra_date_34e0d6_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['source_type', 'source_id'], name='finance_tra_source__6b9cc4_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionline',
            index=models.Index(fields=['account', 'transaction'], name='finance_tra_account_8c7757_idx'),
        ),
    ]
