# Generated by Django 6.0.4 on 2026-08-05 04:04

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('store', '0002_order_orderitem_order_store_order_status_536f03_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(db_index=True, help_text='Short reference, e.g. 1010. Grouped by type — see the seed command. Per-party accounts extend a base code, e.g. 1200-14.', max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, db_index=True, default=None, max_length=20, null=True, unique=True)),
                ('issue_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('payment_terms_days', models.PositiveSmallIntegerField(choices=[(0, 'Due on receipt'), (7, 'Net 7 days'), (15, 'Net 15 days'), (30, 'Net 30 days'), (45, 'Net 45 days')], default=0, help_text='Used to work out the due date when the invoice is issued.')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Whole-invoice discount, on top of any per-line discounts.', max_digits=12)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('notes', models.TextField(blank=True, default='', help_text='Shown at the bottom of the invoice — terms, thanks, instructions.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=15)),
                ('share_token', models.CharField(blank=True, db_index=True, help_text='Lets the client open this invoice without logging in.', max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_invoices', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, help_text='Set when this invoice was generated from a website order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='store.order')),
                ('transaction', models.ForeignKey(blank=True, help_text='The ledger entry created when this invoice was issued.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='finance.transaction')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, default='', max_length=80)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount on this line only, as an amount.', max_digits=12)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.invoice')),
                ('variant', models.ForeignKey(blank=True, help_text='Optional link back to the catalogue.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='store.productvariant')),
            ],
            options={
                'verbose_name': 'Invoice Item',
                'verbose_name_plural': 'Invoice Items',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('party_type', models.CharField(choices=[('wholesale', 'Wholesale / B2B Client'), ('retail', 'Retail Customer'), ('walkin', 'Walk-in'), ('supplier', 'Supplier')], db_index=True, default='wholesale', max_length=15)),
                ('phone', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Warn when unpaid dues go above this. 0 = no limit set.', max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receivable_account', models.OneToOneField(blank=True, help_text='Created automatically the first time this party is invoiced.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='party_owner', to='finance.account')),
            ],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Parties',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='finance.party'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['party_type', 'is_active'], name='finance_par_party_t_546bff_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'issue_date'], name='finance_inv_status_7e531e_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['party', 'status'], name='finance_inv_party_i_b93f53_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date', 'status'], name='finance_inv_due_dat_fb9ca1_idx'),
        ),
    ]
