# Generated by Django 6.0.4 on 2026-08-05 04:08

import finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_account_code_invoice_invoiceitem_party_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(db_index=True, default=finance.models.today),
        ),
    ]
