# Generated by Django 6.0.4 on 2026-08-05 04:26

import django.db.models.deletion
import django.utils.timezone
import finance.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_payments'),
        ('store', '0002_order_orderitem_order_store_order_status_536f03_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_no', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('purchase_type', models.CharField(choices=[('import', 'Import (China / RMB)'), ('local', 'Local purchase (BDT)')], db_index=True, default='import', max_length=10)),
                ('purchase_date', models.DateField(db_index=True, default=finance.models.today)),
                ('fx_rate_rmb_to_bdt', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='৳ per ¥1. Only used on import purchases.', max_digits=10)),
                ('default_per_kg_charge_bdt', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Agent's per-kg rate. Each line can override it.", max_digits=10)),
                ('billed_weight_kg', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='The weight the agent actually billed. Line weights are scaled to match it, so nothing is left unallocated.', max_digits=10)),
                ('extra_cost_bdt', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='BD-side costs — local shipping, repacking, clearing. Spread across the lines by weight.', max_digits=12)),
                ('correction_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Buffer added on top of everything — bank charges, breakage, small unknowns.', max_digits=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ordered', 'Ordered'), ('in_transit', 'In Transit'), ('received', 'Received'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=12)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_purchases', to=settings.AUTH_USER_MODEL)),
                ('order_transaction', models.ForeignKey(blank=True, help_text='Posted when the purchase is marked ordered — goods in transit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases_ordered', to='finance.transaction')),
                ('receipt_transaction', models.ForeignKey(blank=True, help_text='Posted on receipt — moves the value into stock at landed cost.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases_received', to='finance.transaction')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='finance.party')),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'ordering': ['-purchase_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price_rmb', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price per piece in ¥. Import purchases only.', max_digits=12)),
                ('domestic_shipping_rmb', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='China-side shipping for this line, supplier → forwarder, in ¥.', max_digits=12)),
                ('unit_cost_bdt', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price per piece in ৳. Local purchases only.', max_digits=12)),
                ('local_transport_bdt', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Transport for this line. Local purchases only.', max_digits=12)),
                ('entered_weight_kg', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10)),
                ('per_kg_charge_bdt', models.DecimalField(blank=True, decimal_places=2, help_text="Leave blank to use the shipment's default rate.", max_digits=10, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.purchase')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='store.productvariant')),
            ],
            options={
                'verbose_name': 'Purchase Item',
                'verbose_name_plural': 'Purchase Items',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qty_received', models.PositiveIntegerField()),
                ('qty_remaining', models.PositiveIntegerField()),
                ('received_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('purchase_item', models.ForeignKey(blank=True, help_text='Blank for opening stock entered by hand.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='finance.purchaseitem')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_batches', to='store.productvariant')),
            ],
            options={
                'verbose_name': 'Stock Batch',
                'verbose_name_plural': 'Stock Batches',
                'ordering': ['received_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=finance.models.today)),
                ('quantity', models.IntegerField(help_text='Signed — positive in, negative out.')),
                ('reason', models.CharField(choices=[('purchase_receipt', 'Purchase received'), ('sale', 'Sold'), ('sale_return', 'Returned by customer'), ('damage', 'Damaged / lost'), ('adjustment', 'Manual adjustment'), ('opening', 'Opening stock')], db_index=True, max_length=20)),
                ('reference', models.CharField(blank=True, db_index=True, default='', help_text='Order number, purchase number, or whatever explains it.', max_length=60)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch', models.ForeignKey(blank=True, help_text='Set on inbound movements — the batch this created.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_movements', to='finance.stockbatch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='finance.transaction')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='store.productvariant')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='finance.stockbatch')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='finance.stockmovement')),
            ],
            options={
                'verbose_name': 'Stock Consumption',
                'verbose_name_plural': 'Stock Consumptions',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['status', 'purchase_date'], name='finance_pur_status_efd0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['supplier', 'status'], name='finance_pur_supplie_417cd4_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['variant', 'received_date'], name='finance_sto_variant_0a9994_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['variant', 'qty_remaining'], name='finance_sto_variant_caefe6_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['variant', 'date'], name='finance_sto_variant_668b58_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reason', 'date'], name='finance_sto_reason_e41a45_idx'),
        ),
        migrations.AddIndex(
            model_name='stockconsumption',
            index=models.Index(fields=['movement', 'batch'], name='finance_sto_movemen_a21eb4_idx'),
        ),
    ]
