# Generated by Django 6.0.4 on 2026-08-05 04:39

import django.db.models.deletion
import django.utils.timezone
import finance.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_purchases_and_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('notes', models.TextField(blank=True, default='')),
                ('ownership_percent', models.DecimalField(blank=True, decimal_places=3, help_text='Leave blank to work it out from capital contributed.', max_digits=6, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('joined_on', models.DateField(default=finance.models.today)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('equity_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='investor_owner', to='finance.account')),
            ],
            options={
                'verbose_name': 'Investor',
                'verbose_name_plural': 'Investors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_no', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('direction', models.CharField(choices=[('taken', 'Loan taken (we borrowed)'), ('given', 'Loan given (we lent)')], db_index=True, default='taken', max_length=6)),
                ('counterparty_name', models.CharField(help_text='Who lent it to you, or who you lent it to.', max_length=150)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest_rate', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Annual rate as a percentage. 0 for an interest-free loan.', max_digits=6)),
                ('method', models.CharField(choices=[('flat', 'Flat — interest on the original amount'), ('reducing', 'Reducing balance — interest on what is left (EMI)')], default='flat', max_length=10)),
                ('tenure_months', models.PositiveSmallIntegerField(default=12, help_text='Number of monthly installments.')),
                ('start_date', models.DateField(default=finance.models.today)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, help_text="This loan's own account, created when it is recorded.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='finance.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_loans', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='finance.transaction')),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LoanInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('due_date', models.DateField(db_index=True)),
                ('principal_due', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest_due', models.DecimalField(decimal_places=2, max_digits=14)),
                ('principal_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('interest_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('due', 'Due'), ('partial', 'Partly paid'), ('paid', 'Paid')], db_index=True, default='due', max_length=10)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='finance.loan')),
            ],
            options={
                'verbose_name': 'Loan Installment',
                'verbose_name_plural': 'Loan Installments',
                'ordering': ['loan', 'number'],
            },
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=finance.models.today)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(help_text='Where the money came from, or landed.', on_delete=django.db.models.deletion.PROTECT, related_name='loan_payments', to='finance.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_loan_payments', to=settings.AUTH_USER_MODEL)),
                ('installment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.loaninstallment')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.loan')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_payments', to='finance.transaction')),
            ],
            options={
                'verbose_name': 'Loan Payment',
                'verbose_name_plural': 'Loan Payments',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProfitDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('distribution_date', models.DateField(db_index=True, default=finance.models.today)),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('distributed_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_distributions', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profit_distributions', to='finance.transaction')),
            ],
            options={
                'verbose_name': 'Profit Distribution',
                'verbose_name_plural': 'Profit Distributions',
                'ordering': ['-distribution_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProfitShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_percent', models.DecimalField(decimal_places=3, max_digits=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='finance.profitdistribution')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profit_shares', to='finance.investor')),
            ],
            options={
                'verbose_name': 'Profit Share',
                'verbose_name_plural': 'Profit Shares',
                'ordering': ['-amount'],
            },
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['direction', 'status'], name='finance_loa_directi_6d3d3d_idx'),
        ),
        migrations.AddIndex(
            model_name='loaninstallment',
            index=models.Index(fields=['due_date', 'status'], name='finance_loa_due_dat_23a80c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='loaninstallment',
            unique_together={('loan', 'number')},
        ),
    ]
