# Generated by Django 6.0.4 on 2026-08-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_investors_and_loans'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockconsumption',
            name='qty_returned',
            field=models.PositiveIntegerField(default=0, help_text='How much of this consumption has already been given back. Stops the same sale being returned twice.'),
        ),
    ]
