# Generated by Django 6.0.4 on 2026-08-06 03:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_stock_consumption_returns'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='How much you paid the supplier now. Can be a part payment.', max_digits=14),
        ),
        migrations.AddField(
            model_name='purchase',
            name='paid_from',
            field=models.ForeignKey(blank=True, help_text='Which account the money came out of. Leave blank to pay later.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases_paid', to='finance.account'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment',
            field=models.ForeignKey(blank=True, help_text='The payment record created for this purchase, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='finance.payment'),
        ),
    ]
